spring.profiles.active=dev

# Database Settings
spring.jpa.show-sql=true

spring.application.name=mono-server

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
