# Dev Database Settings (H2)
spring.datasource.url=jdbc:h2:file:./chat-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=mono

spring.jpa.hibernate.ddl-auto=update